apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '5m'
        spanEndTimeShift: '5m'
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{$${__tags}} |= "$${__trace.id}"'
      tracesToMetrics:
        datasourceUid: 'prometheus'
        spanStartTimeShift: '5m'
        spanEndTimeShift: '5m'
        queries:
          - name: 'Requests'
            query: 'sum(rate(distrack_requests_total{service_name="$${__service.name}"}[1m]))'
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: 'loki'

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '(?i)(?:trace_?id|trace)["=:\s]+([a-f0-9]{32})'
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace in Tempo'
